### PR TITLE
 Feat (GUI) Home page GUI enhanced

### PR DESCRIPTION
**Pull request by programmerraja**
#6 
Screenshot from 2022-10-15 12-26-56

### CODE REVIEW

**Comment by hitchhicker007** [comment]
@chaudharykapil can you add an image in the background and give some style to the buttons? So that I can merge your PR.

**Comment by programmerraja** [comment]
@hitchhicker007 ok i will do

**Comment by programmerraja** [comment]
@hitchhicker007 Added

**Comment by hitchhicker007** [comment]
@programmerraja Still there are some bugs in GUI, check the below video. Please solve bugs so that I can merge your PR.
https://youtu.be/AdCFaMDE9E4

**Comment by programmerraja** [comment]
@hitchhicker007 sorry i will check and fix it

**Comment by programmerraja** [comment]
@hitchhicker007  are you saying about the bug that is when the user expands the screen the image is misplaced are you telling about that?

**Comment by hitchhicker007** [comment]
> @hitchhicker007 are you saying about the bug that is when the user expands the screen the image is misplaced are you telling about that?

@programmerraja yes

**Comment by programmerraja** [comment]
we can fix that by not allowing a user to expand the screen is it okay for you? that's the only option 
Screenshot from 2022-10-15 15-31-02

**Comment by programmerraja** [comment]
is that okay ? @hitchhicker007

**Comment by programmerraja** [comment]
Hey @hitchhicker007  i just want to u get confirm is that okay but i still wont add that line  i will add that and raise another PR

**Comment by hitchhicker007** [comment]
@programmerraja okay

**Pull request merged**
